name: Atualizar Status do Lote
on:
  workflow_dispatch:
    inputs:
      lote_ids:
        description: "Informe um ou mais IDs, separados por vírgula (ex: _1_A_01,_1_A_02)"
        required: true
        type: string
      novo_status:
        description: Novo status de vendido para TODOS os lotes
        required: true
        type: choice
        options:
          - "TRUE"
          - "FALSE"
        default: "TRUE"
jobs:
  atualizar-arquivo-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Executar script de atualização
        run: >
          node atualizar_lote_ci.js "${{ github.event.inputs.novo_status }}" "${{
          github.event.inputs.lote_ids }}"
      - name: Fazer commit das alterações
        run: >
          git config --global user.name 'GitHub Actions Bot'

          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git add lotes.json

          # A linha abaixo foi simplificada para garantir a compatibilidade com o parser YAML

          git diff --staged --quiet || git commit -m "CI: Atualiza status para ${{ github.event.inputs.novo_status }} nos lotes: ${{ github.event.inputs.lote_ids }}"

          git push
